# Tracking CRM Framework - Template de Deployment
# Copia este archivo como docker-compose.yml y configura las variables

version: '3.8'

services:
  # Base de datos PostgreSQL
  tracking_db:
    image: postgres:15-alpine
    container_name: tracking_crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-tracking_crm}
      POSTGRES_USER: ${DATABASE_USER:-tracking_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secure_password_2024}
    volumes:
      - tracking_db_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT_HOST:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-tracking_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend de tracking
  backend:
    build:
      context: ./backend/template
      dockerfile: Dockerfile
    container_name: tracking_crm_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT_HOST:-3001}:3001"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-tracking_user}:${DATABASE_PASSWORD:-secure_password_2024}@tracking_db:5432/${DATABASE_NAME:-tracking_crm}
      - BACKEND_URL=http://localhost:3001
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_key_2024_change_me}
      - API_KEY_USER_1=${API_KEY_USER_1:-default_api_key_user_1_change_me}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - DEFAULT_BUSINESS_ID=${DEFAULT_BUSINESS_ID:-1}
      - TRACKING_SESSION_TIMEOUT_MS=1800000 # 30 minutos
      - TRACKING_DEBUG_MODE=true
    depends_on:
      tracking_db:
        condition: service_healthy
    volumes:
      # Monta el código fuente para desarrollo en tiempo real
      - ./backend/template/src:/app/src

volumes:
  tracking_db_data:
    driver: local
